name: CICD

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1

      - name: Local Docker API Test
        run: | 
          sam local invoke crcServerlessFunction -e events/event.json
          sam local start-api  > /dev/null 2>&1 &
        # "http://127.0.0.1:3000/Prod/johnkoenigninjasitecounter/"

      - name: Check https status
        uses: lakuapik/gh-actions-http-status@v1
        with:
          sites: '["https://johnkoenig.ninja", "https://40vk7pg898.execute-api.us-east-2.amazonaws.com/Prod/johnkoenigninjasitecounter/"]'
          expected: '[200, 200]'

      # sam build 
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - run: sam build --use-container

      # sam deploy
      - run: sam deploy #--no-confirm-changeset --no-fail-on-empty-changeset --stack-name sitecounter --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-12lkd9h2oeinw --capabilities CAPABILITY_IAM --region us-east-2
